#[derive(Debug)]
#[repr(u16)]
/// Enums for character ID
pub enum CharacterID {
    MByleth,
    FByleth,
    Edelgard,
    Dimitri,
    Claude,
    Hubert,
    Ferdinand,
    Linhardt,
    Caspar,
    Bernadetta,
    Dorothea,
    Petra,
    Dedue,
    Felix,
    Ashe,
    Sylvain,
    Mercedes,
    Annette,
    Ingrid,
    Lorenz,
    Raphael,
    Ignatz,
    Lysithea,
    Marianne,
    Hilda,
    Leonie,
    Seteth,
    Flayn,
    Hanneman,
    Manuela,
    Gilbert,
    Alois,
    Catherine,
    Shamir,
    Cyril,
    Jeralt,
    Rhea,
    Sothis,
    Kronya,
    Solon,
    Thales,
    Cornelia,
    DeathKnight_,
    Kostas,
    Lonato,
    Miklan,
    Randolph,
    _FlameEmperor_,
    Anna,
    Jeritza,
    Rodrigue,
    Judith,
    Nader,
    Monica,
    _LordArundel_,
    Tomas,
    Nemesis,
    Yuri = 1040,
    Balthus = 1041,
    Constance = 1042,
    Hapi = 1043,
    ChurchOfSeirosDudeWithMinorCrest = 1044,
    Jeritza_Playable = 1045,
    Anna_Playable = 1046,
}
