#[derive(Debug)]
#[repr(u8)]
pub enum ItemID {
    Vulnerary,
    Concoction,
    Elixir,
    Intermediate_Seal = 3,
    Advanced_Seal = 4,
    Combined_Seal = 5,
    Master_Seal = 6,
    Torch_Item,
    Bullion,
    Large_Bullion,
    Extra_Large_Bullion,
    Antitoxin,
    Pure_Water,
    Door_Key,
    Chest_Key,
    Master_Key,
    Seraph_Robe,
    Energy_Drop,
    Spirit_Dust,
    Secret_Book,
    Speed_Wing,
    Goddess_Icon,
    Giant_Shell,
    Talisman,
    Black_Pearl,
    Shoes_of_the_Wind,
    Grilled_Duck,
    Fried_Boar,
    Magical_Herb_Salad,
    Dried_Plums,
    Pike_Casserole,
    Bear_and_Vegetable_Soup,
    Fried_Gar,
    Fried_Queen_Koi,
    Sculpin_Gratin,
    Grilled_Wolverine_and_Herbs,
    Grilled_Duck_plus,
    Fried_Boar_plus,
    Magical_Herb_Salad_plus,
    Dried_Plums_plus,
    Pike_Casserole_plus,
    Bear_and_Vegetable_Soup_plus,
    Fried_Gar_plus,
    Fried_Queen_Koi_plus,
    Sculpin_Gratin_plus,
    Grilled_Wolverine_and_Herbs_plus,
    Albinea_Juice,
    Grilled_Chicken_and_Herbs,
    Roast_Duck,
    Grilled_Chicken_and_Herbs_plus,
    Roast_Duck_plus,
    Sacred_Galewind_Shoes,
    Sacred_Floral_Robe,
    Sacred_Snowmelt_Drop,
    Sacred_Moonstone,
    Thorn_Dragon_Sign = 126,
    Wind_Dragon_Sign = 127,
    Sky_Dragon_Sign,
    Crusher_Dragon_Sign,
    Shield_Dragon_Sign,
    Bloom_Dragon_Sign,
    Light_Dragon_Sign,
    Flame_Dragon_Sign,
    Grim_Dragon_Sign,
    Craft_Dragon_Sign,
    Kalpa_Dragon_Sign,
    Earth_Dragon_Sign,
    Ice_Dragon_Sign,
    Fissure_Dragon_Sign,
    Water_Dragon_Sign,
    Storm_Dragon_Sign,
    Lightning_Dragon_Sign,
    Dark_Dragon_Sign,
    Star_Dragon_Sign,
    Snow_Dragon_Sign,
    Aegis_Dragon_Sign,
    Crest_Stone,
    Rocky_Burdock,
    Premiun_Magic_Herbs,
    Ailell_Pomegranate,
    Speed_Carrot,
    Miracle_Bean,
    Ambrosia,
    White_Verona,
    Golden_Apple,
    Fruit_of_Life,
    Dark_Seal = 157,
    Beginner_Seal = 158,
}
